### ISSUE TITLE
Any reason to only use BTC-USD pair?

### ISSUE THREAD

**Issue by nitrocode** [gsugar87/CryptoTaxes#1]

**Comment by gsugar87** [comment]
The code should be able to handle any coin pair, but for tax purposes each coin-coin transaction is treated as two coin-USD transactions.  For example, If you bought 100 litecoin with 1 bitcoin, the code will treat this as you selling bitcoin for USD and buying litecoin with that USD.  It looks up the price of bitcoin during the time you made the trade to get the USD conversions.  If bitcoin was trading at 9000 at the time of your trade, then the buy 100 litecoin for 1 bitcoin trade would become:
1) Sell 1 bitcoin to get 9000 USD
2) Buy 100 litecoins at 90 USD each (for a total of 9000 USD)

**Comment by nitrocode** [comment]
Ah okay. By the way, I really admire your work! I was considering bitcoin.tax until I found your script.

I noticed that you don't have a license set up for your code. Do you mind if I fork your project and give you credit? I'd like to expand on it to handle all currency pairs and add more exchanges.

I saw that you don't have to create 8949s for every 14 transactions. Instead you can put the summary on the 8949 and put each transaction on the [continuation sheet 1040 (Schedule D-1)](https://www.irs.gov/pub/irs-prior/f1040sd1--2010.pdf).

**Comment by gsugar87** [comment]
Sure! Feel free to fork the code.  I didn't know about the continuation sheet- thanks for letting me know!
